FROM feathercoin/centos7-dep
RUN mkdir /usr/src && cd /usr/src && wget https://www.openssl.org/source/openssl-1.0.1l.tar.gz
RUN cd /usr/src && tar wget https://www.openssl.org/source/openssl-1.0.1l.tar.gz
